<?php

/**
 * Implementation of hook_views_api().
 */
function as_exports_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'as_exports'),
  );
}

function as_exports_flag_default_flags() {
  $flags = array();
  // Exported flag: "Favorite".
  $flags[] = array (
    'content_type' => 'node',
    'name' => 'favorite',
    'title' => 'Favorite',
    'global' => '0',
    'types' => 
    array (
      0 => 'comment',
      1 => 'question',
    ),
    'flag_short' => 'favorite',
    'flag_long' => '',
    'flag_message' => '',
    'unflag_short' => 'unfavorite',
    'unflag_long' => '',
    'unflag_message' => '',
    'unflag_denied_text' => '',
    'link_type' => 'toggle',
    'roles' => 
    array (
      'flag' => 
      array (
        0 => 2,
      ),
      'unflag' => 
      array (
        0 => 2,
      ),
    ),
    'show_on_page' => 1,
    'show_on_teaser' => 1,
    'show_on_form' => 0,
    'access_author' => 'others',
    'i18n' => 0,
    'status' => TRUE,
    'api_version' => 2,
  );

  // Exported flag: "Best".
  $flags[] = array (
    'content_type' => 'node',
    'name' => 'best',
    'title' => 'Best',
    'global' => '0',
    'types' => 
    array (
      0 => 'comment',
      1 => 'question',
    ),
    'flag_short' => 'best answer',
    'flag_long' => '',
    'flag_message' => '',
    'unflag_short' => 'not best',
    'unflag_long' => '',
    'unflag_message' => '',
    'unflag_denied_text' => '',
    'link_type' => 'toggle',
    'roles' => 
    array (
      'flag' => 
      array (
        0 => 2,
      ),
      'unflag' => 
      array (
        0 => 2,
      ),
    ),
    'show_on_page' => 0,
    'show_on_teaser' => 0,
    'show_on_form' => 0,
    'access_author' => 'others',
    'i18n' => 0,
    'status' => TRUE,
    'api_version' => 2,
  );

  // Exported flag: "Wikify".
  $flags[] = array (
    'content_type' => 'node',
    'name' => 'wikify',
    'title' => 'Wikify',
    'global' => '1',
    'types' => 
    array (
      0 => 'question',
      1 => 'comment',
    ),
    'flag_short' => 'wikify',
    'flag_long' => 'Make this content editable by any contributor',
    'flag_message' => '',
    'unflag_short' => 'unwikify',
    'unflag_long' => 'Restrict editing of this content to the author',
    'unflag_message' => '',
    'unflag_denied_text' => '',
    'link_type' => 'normal',
    'roles' => 
    array (
      'flag' => 
      array (
        0 => 3,
      ),
      'unflag' => 
      array (
        0 => 3,
      ),
    ),
    'show_on_page' => 1,
    'show_on_teaser' => 1,
    'show_on_form' => 0,
    'access_author' => '',
    'i18n' => 0,
    'status' => TRUE,
    'api_version' => 2,
  );
  // Exported flag: "Offensive".
  $flags[] = array (
    'content_type' => 'node',
    'name' => 'offensive',
    'title' => 'Offensive',
    'global' => '0',
    'types' => 
    array (
      0 => 'question',
      1 => 'comment',
    ),
    'flag_short' => 'flag',
    'flag_long' => '',
    'flag_message' => '',
    'unflag_short' => 'unflag',
    'unflag_long' => '',
    'unflag_message' => '',
    'unflag_denied_text' => '',
    'link_type' => 'confirm',
    'roles' => 
    array (
      'flag' => 
      array (
        0 => 4,
      ),
      'unflag' => 
      array (
        0 => 4,
      ),
    ),
    'show_on_page' => 1,
    'show_on_teaser' => 1,
    'show_on_form' => 0,
    'access_author' => '',
    'i18n' => 0,
    'flag_confirmation' => 'Are you sure you want to flag this content as offensive?',
    'unflag_confirmation' => 'Are you sure you want to remove the offensive flag from this content?',
    'status' => TRUE,
    'api_version' => 2,
  );
  // Exported flag: "Interesting".
  $flags[] = array (
    'content_type' => 'term',
    'name' => 'interesting',
    'title' => 'Interesting',
    'global' => '0',
    'types' => 
    array (
      0 => variable_get('as_exports_vid', 1),
    ),
    'flag_short' => 'watch',
    'flag_long' => '',
    'flag_message' => '',
    'unflag_short' => 'stop watching',
    'unflag_long' => '',
    'unflag_message' => '',
    'unflag_denied_text' => '',
    'link_type' => 'toggle',
    'roles' => 
    array (
      'flag' => 
      array (
        0 => 2,
      ),
      'unflag' => 
      array (
        0 => 2,
      ),
    ),
    'show_on_term_page' => 1,
    'status' => TRUE,
    'api_version' => 2,
  );
  // Exported flag: "Ignored".
  $flags[] = array (
    'content_type' => 'term',
    'name' => 'ignored',
    'title' => 'Ignored',
    'global' => '0',
    'types' => 
    array (
      0 => variable_get('as_exports_vid', 1),
    ),
    'flag_short' => 'ignore',
    'flag_long' => '',
    'flag_message' => '',
    'unflag_short' => 'stop ignoring',
    'unflag_long' => '',
    'unflag_message' => '',
    'unflag_denied_text' => '',
    'link_type' => 'toggle',
    'roles' => 
    array (
      'flag' => 
      array (
        0 => 2,
      ),
      'unflag' => 
      array (
        0 => 2,
      ),
    ),
    'show_on_term_page' => 1,
    'status' => TRUE,
    'api_version' => 2,
  );
  return $flags;
}